version: '3'

services:
  db:
    container_name: ${MONGO_DB} # Container Name
    image: mongo:6.0 # Image to pull
    volumes:
      - poke-vol:/data/db # Where to save data volume-name:path/where/image/save/data
    restart: always
    environment: # env
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth'] # Command to execute

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB}
    ports:
      - 8080:8081
    restart: always

  poke-app:
    container_name: pokemon-nest-app
    image: klerith/pokemon-nest-app:1.0.0
    depends_on:
      - db
      - mongo-express
    environment:
      MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB}:27017
      DB_NAME: ${MONGO_DB}
    ports:
      - 3000:3000
    restart: always

volumes:
  poke-vol:
    external: false