version: '3'


services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15.1
    volumes:
#      - postgres-db:/var/lib/postgresql/data
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
  
  pgAdmin:
    image: dpage/pgadmin4:6.17
    depends_on:
      - postgres-db
    volumes:
#     - postgres-db:/var/lib/postgresql/data
      - ./data/pgAdmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    ports:
      - "8080:80"

# volumes:
#   postgres-db:
#     external: true